// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BebaBackendClient is the client API for BebaBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BebaBackendClient interface {
	TestHello(ctx context.Context, in *TestHelloRequest, opts ...grpc.CallOption) (*TestHelloResponse, error)
	GetVeterinarians(ctx context.Context, in *VetRequest, opts ...grpc.CallOption) (BebaBackend_GetVeterinariansClient, error)
	UpdateVeterian(ctx context.Context, in *Veterinary, opts ...grpc.CallOption) (*Veterinary, error)
	UpdateFarmer(ctx context.Context, in *Farmer, opts ...grpc.CallOption) (*Farmer, error)
	GetFarmer(ctx context.Context, in *FarmerRequest, opts ...grpc.CallOption) (*Farmer, error)
	ScheduleSession(ctx context.Context, in *TreatmentSession, opts ...grpc.CallOption) (*TreatmentSession, error)
}

type bebaBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewBebaBackendClient(cc grpc.ClientConnInterface) BebaBackendClient {
	return &bebaBackendClient{cc}
}

func (c *bebaBackendClient) TestHello(ctx context.Context, in *TestHelloRequest, opts ...grpc.CallOption) (*TestHelloResponse, error) {
	out := new(TestHelloResponse)
	err := c.cc.Invoke(ctx, "/beba_backend.BebaBackend/TestHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bebaBackendClient) GetVeterinarians(ctx context.Context, in *VetRequest, opts ...grpc.CallOption) (BebaBackend_GetVeterinariansClient, error) {
	stream, err := c.cc.NewStream(ctx, &BebaBackend_ServiceDesc.Streams[0], "/beba_backend.BebaBackend/GetVeterinarians", opts...)
	if err != nil {
		return nil, err
	}
	x := &bebaBackendGetVeterinariansClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BebaBackend_GetVeterinariansClient interface {
	Recv() (*Veterinary, error)
	grpc.ClientStream
}

type bebaBackendGetVeterinariansClient struct {
	grpc.ClientStream
}

func (x *bebaBackendGetVeterinariansClient) Recv() (*Veterinary, error) {
	m := new(Veterinary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bebaBackendClient) UpdateVeterian(ctx context.Context, in *Veterinary, opts ...grpc.CallOption) (*Veterinary, error) {
	out := new(Veterinary)
	err := c.cc.Invoke(ctx, "/beba_backend.BebaBackend/UpdateVeterian", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bebaBackendClient) UpdateFarmer(ctx context.Context, in *Farmer, opts ...grpc.CallOption) (*Farmer, error) {
	out := new(Farmer)
	err := c.cc.Invoke(ctx, "/beba_backend.BebaBackend/UpdateFarmer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bebaBackendClient) GetFarmer(ctx context.Context, in *FarmerRequest, opts ...grpc.CallOption) (*Farmer, error) {
	out := new(Farmer)
	err := c.cc.Invoke(ctx, "/beba_backend.BebaBackend/GetFarmer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bebaBackendClient) ScheduleSession(ctx context.Context, in *TreatmentSession, opts ...grpc.CallOption) (*TreatmentSession, error) {
	out := new(TreatmentSession)
	err := c.cc.Invoke(ctx, "/beba_backend.BebaBackend/ScheduleSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BebaBackendServer is the server API for BebaBackend service.
// All implementations must embed UnimplementedBebaBackendServer
// for forward compatibility
type BebaBackendServer interface {
	TestHello(context.Context, *TestHelloRequest) (*TestHelloResponse, error)
	GetVeterinarians(*VetRequest, BebaBackend_GetVeterinariansServer) error
	UpdateVeterian(context.Context, *Veterinary) (*Veterinary, error)
	UpdateFarmer(context.Context, *Farmer) (*Farmer, error)
	GetFarmer(context.Context, *FarmerRequest) (*Farmer, error)
	ScheduleSession(context.Context, *TreatmentSession) (*TreatmentSession, error)
	mustEmbedUnimplementedBebaBackendServer()
}

// UnimplementedBebaBackendServer must be embedded to have forward compatible implementations.
type UnimplementedBebaBackendServer struct {
}

func (UnimplementedBebaBackendServer) TestHello(context.Context, *TestHelloRequest) (*TestHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestHello not implemented")
}
func (UnimplementedBebaBackendServer) GetVeterinarians(*VetRequest, BebaBackend_GetVeterinariansServer) error {
	return status.Errorf(codes.Unimplemented, "method GetVeterinarians not implemented")
}
func (UnimplementedBebaBackendServer) UpdateVeterian(context.Context, *Veterinary) (*Veterinary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVeterian not implemented")
}
func (UnimplementedBebaBackendServer) UpdateFarmer(context.Context, *Farmer) (*Farmer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFarmer not implemented")
}
func (UnimplementedBebaBackendServer) GetFarmer(context.Context, *FarmerRequest) (*Farmer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFarmer not implemented")
}
func (UnimplementedBebaBackendServer) ScheduleSession(context.Context, *TreatmentSession) (*TreatmentSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleSession not implemented")
}
func (UnimplementedBebaBackendServer) mustEmbedUnimplementedBebaBackendServer() {}

// UnsafeBebaBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BebaBackendServer will
// result in compilation errors.
type UnsafeBebaBackendServer interface {
	mustEmbedUnimplementedBebaBackendServer()
}

func RegisterBebaBackendServer(s grpc.ServiceRegistrar, srv BebaBackendServer) {
	s.RegisterService(&BebaBackend_ServiceDesc, srv)
}

func _BebaBackend_TestHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BebaBackendServer).TestHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beba_backend.BebaBackend/TestHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BebaBackendServer).TestHello(ctx, req.(*TestHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BebaBackend_GetVeterinarians_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BebaBackendServer).GetVeterinarians(m, &bebaBackendGetVeterinariansServer{stream})
}

type BebaBackend_GetVeterinariansServer interface {
	Send(*Veterinary) error
	grpc.ServerStream
}

type bebaBackendGetVeterinariansServer struct {
	grpc.ServerStream
}

func (x *bebaBackendGetVeterinariansServer) Send(m *Veterinary) error {
	return x.ServerStream.SendMsg(m)
}

func _BebaBackend_UpdateVeterian_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Veterinary)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BebaBackendServer).UpdateVeterian(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beba_backend.BebaBackend/UpdateVeterian",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BebaBackendServer).UpdateVeterian(ctx, req.(*Veterinary))
	}
	return interceptor(ctx, in, info, handler)
}

func _BebaBackend_UpdateFarmer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Farmer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BebaBackendServer).UpdateFarmer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beba_backend.BebaBackend/UpdateFarmer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BebaBackendServer).UpdateFarmer(ctx, req.(*Farmer))
	}
	return interceptor(ctx, in, info, handler)
}

func _BebaBackend_GetFarmer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FarmerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BebaBackendServer).GetFarmer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beba_backend.BebaBackend/GetFarmer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BebaBackendServer).GetFarmer(ctx, req.(*FarmerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BebaBackend_ScheduleSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreatmentSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BebaBackendServer).ScheduleSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beba_backend.BebaBackend/ScheduleSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BebaBackendServer).ScheduleSession(ctx, req.(*TreatmentSession))
	}
	return interceptor(ctx, in, info, handler)
}

// BebaBackend_ServiceDesc is the grpc.ServiceDesc for BebaBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BebaBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beba_backend.BebaBackend",
	HandlerType: (*BebaBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestHello",
			Handler:    _BebaBackend_TestHello_Handler,
		},
		{
			MethodName: "UpdateVeterian",
			Handler:    _BebaBackend_UpdateVeterian_Handler,
		},
		{
			MethodName: "UpdateFarmer",
			Handler:    _BebaBackend_UpdateFarmer_Handler,
		},
		{
			MethodName: "GetFarmer",
			Handler:    _BebaBackend_GetFarmer_Handler,
		},
		{
			MethodName: "ScheduleSession",
			Handler:    _BebaBackend_ScheduleSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVeterinarians",
			Handler:       _BebaBackend_GetVeterinarians_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/service.proto",
}
